version: '2'

networks:
  default:
    name: bestrunner

volumes:
  frontend_node_modules:
  backend_node_modules:

services:
  traefik:
    image: traefik:latest
    ports:
      - "80:80"
    restart: always
    command:
      - --api=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entryPoints.http.address=:80
      - --log.level=INFO
      - --accessLog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: Host(`traefik.${APP_HOST}`)
      traefik.http.routers.traefik.service: api@internal
  frontend:
    image: node:16.13.2
    command: sh -c "yarn install && yarn start"
    ports:
      - 3000:3000
    volumes:
      - frontend_node_modules:/app/node_modules
      - ./frontend:/app
    working_dir: /app
    labels:
      traefik.enable: "true"
      traefik.http.routers.frontend.rule: Host(`${APP_HOST}`)
  backend:
    image: node:16.13.2
    env_file:
      - ./backend/.env
    command: sh -c "yarn install && yarn build && yarn start"
    ports:
      - 5000:5000
    volumes:
      - backend_node_modules:/app/node_modules
      - ./backend:/app
    working_dir: /app
    labels:
      traefik.enable: "true"
      traefik.http.routers.backend.rule: Host(`api.${APP_HOST}`)     